//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/RTS Command System/Controls/RTSControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RTSControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RTSControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RTSControls"",
    ""maps"": [
        {
            ""name"": ""RTS"",
            ""id"": ""2bea8139-d3f4-48f1-b77d-6e836aead4c7"",
            ""actions"": [
                {
                    ""name"": ""LeftMouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""baba6e54-754e-46ca-96b8-c1bb079b7032"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftMouseDrag"",
                    ""type"": ""Button"",
                    ""id"": ""edcaf39e-4e68-4f20-8879-238162504399"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightMouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""d995c8ea-ff73-4305-86d5-1b4adbb88c42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseDrag"",
                    ""type"": ""Button"",
                    ""id"": ""134ddd15-b830-4451-bba4-99fa64783786"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""7c243e8c-6085-47e7-9103-a1d808053662"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraY"",
                    ""type"": ""Value"",
                    ""id"": ""88fcd370-802f-4240-8669-c38fbed28679"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraX"",
                    ""type"": ""Value"",
                    ""id"": ""1b819017-27a4-46cf-901e-1233424b1b91"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""5b73fdbf-5b17-4487-829f-5d4b5d3316ae"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""78754df3-cfcc-4f0c-984e-2c97115deab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9f442bd2-5cd5-4af0-8496-04a9cf508b36"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96926f50-b7e6-414a-8c51-52e653604d8e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ac362e-a97c-4e2c-9447-3a1e52f2e48c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9103eabd-3c99-4f55-870a-e0d54537f505"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50ec5f2f-4ec4-4be7-9aa0-b70e76dd40a5"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""0b735aec-789c-45d0-b4ed-3cd06a80a2cc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""728b9cd7-212e-4837-8d9e-266dd62d6188"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5963f2da-f63c-4154-b546-e37bd81a3014"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""UpDown"",
                    ""id"": ""f9f71389-5125-4b8b-95a8-d4c61ef77b54"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b9255980-4395-4ac2-85d3-4d10ee4dd566"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4931c149-1475-4129-bc80-8fbde11b57c1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""4dc677c7-91b1-48ab-8b37-c79d7c221f9e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7cc7410b-1eed-4a53-8d73-3072d91efd6f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""126ba97a-8a59-4ea2-8968-6b95b2bb0cab"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""6475dabb-5934-4ece-badb-55582aa70d20"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5a08e342-aae3-4ebe-891d-61fba3c537c0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2e956a32-4666-4a0b-a332-efe32b448abf"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MouseWheel"",
                    ""id"": ""c8cb28f5-eba1-4dd7-8248-793a58005a64"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cd79565d-c9bb-4ee3-b7d4-53a8df18d180"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a6336603-99b9-4a66-8977-6ae8cca93c65"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0e0747a5-4457-4ac3-a52e-704b10529cf9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RTS
        m_RTS = asset.FindActionMap("RTS", throwIfNotFound: true);
        m_RTS_LeftMouseClick = m_RTS.FindAction("LeftMouseClick", throwIfNotFound: true);
        m_RTS_LeftMouseDrag = m_RTS.FindAction("LeftMouseDrag", throwIfNotFound: true);
        m_RTS_RightMouseClick = m_RTS.FindAction("RightMouseClick", throwIfNotFound: true);
        m_RTS_RightMouseDrag = m_RTS.FindAction("RightMouseDrag", throwIfNotFound: true);
        m_RTS_MousePosition = m_RTS.FindAction("MousePosition", throwIfNotFound: true);
        m_RTS_CameraY = m_RTS.FindAction("CameraY", throwIfNotFound: true);
        m_RTS_CameraX = m_RTS.FindAction("CameraX", throwIfNotFound: true);
        m_RTS_CameraZoom = m_RTS.FindAction("CameraZoom", throwIfNotFound: true);
        m_RTS_Escape = m_RTS.FindAction("Escape", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RTS
    private readonly InputActionMap m_RTS;
    private IRTSActions m_RTSActionsCallbackInterface;
    private readonly InputAction m_RTS_LeftMouseClick;
    private readonly InputAction m_RTS_LeftMouseDrag;
    private readonly InputAction m_RTS_RightMouseClick;
    private readonly InputAction m_RTS_RightMouseDrag;
    private readonly InputAction m_RTS_MousePosition;
    private readonly InputAction m_RTS_CameraY;
    private readonly InputAction m_RTS_CameraX;
    private readonly InputAction m_RTS_CameraZoom;
    private readonly InputAction m_RTS_Escape;
    public struct RTSActions
    {
        private @RTSControls m_Wrapper;
        public RTSActions(@RTSControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftMouseClick => m_Wrapper.m_RTS_LeftMouseClick;
        public InputAction @LeftMouseDrag => m_Wrapper.m_RTS_LeftMouseDrag;
        public InputAction @RightMouseClick => m_Wrapper.m_RTS_RightMouseClick;
        public InputAction @RightMouseDrag => m_Wrapper.m_RTS_RightMouseDrag;
        public InputAction @MousePosition => m_Wrapper.m_RTS_MousePosition;
        public InputAction @CameraY => m_Wrapper.m_RTS_CameraY;
        public InputAction @CameraX => m_Wrapper.m_RTS_CameraX;
        public InputAction @CameraZoom => m_Wrapper.m_RTS_CameraZoom;
        public InputAction @Escape => m_Wrapper.m_RTS_Escape;
        public InputActionMap Get() { return m_Wrapper.m_RTS; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RTSActions set) { return set.Get(); }
        public void SetCallbacks(IRTSActions instance)
        {
            if (m_Wrapper.m_RTSActionsCallbackInterface != null)
            {
                @LeftMouseClick.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseClick;
                @LeftMouseClick.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseClick;
                @LeftMouseClick.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseClick;
                @LeftMouseDrag.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseDrag;
                @LeftMouseDrag.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseDrag;
                @LeftMouseDrag.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnLeftMouseDrag;
                @RightMouseClick.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseClick;
                @RightMouseClick.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseClick;
                @RightMouseClick.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseClick;
                @RightMouseDrag.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseDrag;
                @RightMouseDrag.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseDrag;
                @RightMouseDrag.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnRightMouseDrag;
                @MousePosition.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnMousePosition;
                @CameraY.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraY;
                @CameraY.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraY;
                @CameraY.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraY;
                @CameraX.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraX;
                @CameraX.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraX;
                @CameraX.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraX;
                @CameraZoom.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnCameraZoom;
                @Escape.started -= m_Wrapper.m_RTSActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_RTSActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_RTSActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_RTSActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftMouseClick.started += instance.OnLeftMouseClick;
                @LeftMouseClick.performed += instance.OnLeftMouseClick;
                @LeftMouseClick.canceled += instance.OnLeftMouseClick;
                @LeftMouseDrag.started += instance.OnLeftMouseDrag;
                @LeftMouseDrag.performed += instance.OnLeftMouseDrag;
                @LeftMouseDrag.canceled += instance.OnLeftMouseDrag;
                @RightMouseClick.started += instance.OnRightMouseClick;
                @RightMouseClick.performed += instance.OnRightMouseClick;
                @RightMouseClick.canceled += instance.OnRightMouseClick;
                @RightMouseDrag.started += instance.OnRightMouseDrag;
                @RightMouseDrag.performed += instance.OnRightMouseDrag;
                @RightMouseDrag.canceled += instance.OnRightMouseDrag;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @CameraY.started += instance.OnCameraY;
                @CameraY.performed += instance.OnCameraY;
                @CameraY.canceled += instance.OnCameraY;
                @CameraX.started += instance.OnCameraX;
                @CameraX.performed += instance.OnCameraX;
                @CameraX.canceled += instance.OnCameraX;
                @CameraZoom.started += instance.OnCameraZoom;
                @CameraZoom.performed += instance.OnCameraZoom;
                @CameraZoom.canceled += instance.OnCameraZoom;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public RTSActions @RTS => new RTSActions(this);
    public interface IRTSActions
    {
        void OnLeftMouseClick(InputAction.CallbackContext context);
        void OnLeftMouseDrag(InputAction.CallbackContext context);
        void OnRightMouseClick(InputAction.CallbackContext context);
        void OnRightMouseDrag(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnCameraY(InputAction.CallbackContext context);
        void OnCameraX(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
}
